FROM coreoasis/oasis_base:0.398.1

RUN mkdir /var/www/oasis
RUN mkdir /var/www/oasis/keys_server
COPY ./src/keys_server/__init__.py.base /var/www/oasis/keys_server/__init__.py
RUN echo "\nfrom .Deterministic import *" >> /var/www/oasis/keys_server/__init__.py
COPY ./src/keys_server/utils.py /var/www/oasis/keys_server/
COPY ./src/keys_server/requirements.txt /var/www/oasis/keys_server/
RUN mkdir /var/www/oasis/keys_server/Deterministic
COPY ./src/keys_server/Deterministic/ /var/www/oasis/keys_server/Deterministic/
COPY ./src/keys_server/Deterministic/KeysServer.ini /var/www/oasis/oasis_keys_server/

RUN mkdir /var/oasis
RUN mkdir /var/oasis/keys_data && \
    chown www-data:www-data /var/oasis/keys_data && \
    chmod -R 744 /var/oasis/keys_data
COPY ./keys_data/Deterministic/ /var/oasis/keys_data/

RUN pip install -r /var/www/oasis/keys_server/requirements.txt && \
    pip install -r /var/www/oasis/keys_server/Deterministic/requirements.txt

ENTRYPOINT startup.sh
