version: "2"
services:


 oasislmf_deterministic_keys_server:
  restart: always
  container_name: deterministic_keys_server
  image: coreoasis/deterministic_keys_server:latest
  ports:
   - 9001:80


 oasislmf_deterministic_worker:
  restart: always
  image: coreoasis/model_execution_worker:latest
  container_name: deterministic_worker 
  volumes:
   - /home/ubuntu/efs/Test-Porfolio/model_data:/var/oasis/model_data/Deterministic-Model-Test
   - /home/ubuntu/upload:/var/www/oasis/upload:rw
   - /home/ubuntu/download:/var/www/oasis/download:rw
   - /tmp:/tmp
  # Prevent the machine craching due to excessive memory pressure
  mem_limit: 50g
  # Vulnerability data is loaded in shm
  shm_size: 15g
  # Required to allow GDB
  privileged: true
  environment:
   - MODEL_SUPPLIER_ID=OasisLMF
   - MODEL_VERSION_ID=Deterministic
   - OASIS_API_KTOOLS_BATCH_COUNT=-1

