version: "2"
services:



 oasislmf_piwind_keys_server:
  container_name: piwind_keys_server
  image: coreoasis/piwind_keys_server:latest
  ports:
   - 9001:80



 testportfolio100_worker:
  restart: always
  image: coreoasis/model_execution_worker:latest
  container_name: Deterministic-Model-Test_worker 
  volumes:
   - /home/ubuntu/efs/Test-Porfolio/model_data:/var/oasis/model_data/Deterministic-Model-Test
   - /home/ubuntu/upload:/var/www/oasis/upload:rw
   - /home/ubuntu/download:/var/www/oasis/download:rw
   - /tmp:/tmp
  # Prevent the machine craching due to excessive memory pressure
  mem_limit: 50g
  # Vulnerability data is loaded in shm
  shm_size: 15g
  # Required to allow GDB
  privileged: true
  environment:
   - MODEL_SUPPLIER_ID=Deterministic-Model-Test
   - MODEL_VERSION_ID=Deterministic-Model-Test
   - LOCK_FILE = '/tmp/tmp_ktools_lock_file'
   - DO_CLEAR_WORKING = True
   # Sets the number of cores used by the model execution
   # Set to -1 to use all available cores
   - OASIS_API_KTOOLS_BATCH_COUNT=-1

