FROM coreoasis/custom_keys_server:latest

RUN mkdir /var/www/oasis/keys_server
COPY ./src/keys_server/__init__.py.base /var/www/oasis/keys_server/__init__.py
RUN echo "\nfrom .Deterministic-Model-Test import *" >> /var/www/oasis/keys_server/__init__.py
COPY ./src/keys_server/utils.py /var/www/oasis/keys_server/
COPY ./src/keys_server/requirements.txt /var/www/oasis/keys_server/
RUN mkdir /var/www/oasis/keys_server/Deterministic-Model-Test
COPY ./src/keys_server/Deterministic-Model-Test/ /var/www/oasis/keys_server/Deterministic-Model-Test/
COPY ./src/keys_server/Deterministic-Model-Test/KeysServer.ini /var/www/oasis/oasis_keys_server/

RUN mkdir /var/oasis/keys_data && \
    chown www-data:www-data /var/oasis/keys_data && \
    chmod -R 744 /var/oasis/keys_data
COPY ./keys_data/Deterministic-Model-Test/ /var/oasis/keys_data/

RUN pip install -r /var/www/oasis/keys_server/requirements.txt && \
    pip install -r /var/www/oasis/keys_server/Deterministic-Model-Test/requirements.txt

ENTRYPOINT startup.sh
